FROM golang:1.16-alpine

# Install curl for testing API
RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*

# Set necessary environment variables
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the application
RUN go build -o glance .

# Move to /dist directory as the place for resulting binary folder
WORKDIR /dist

# Copy binary from build to main folder
RUN cp /build/.env . && cp /build/glance .

# Export necessary port
EXPOSE 8080

# Command to run when starting the container
CMD ["/build/glance"]

